title: OvrK12
baseurl: ""
url: "https://OvrK12.github.io/"
author_name: "Kraus, Oliver"
permalink: "/blog/:title/"

plugins:
  - jekyll-postcss-v2
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-scholar

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true
scholar:
  bibliography: papers.bib
  bibliography_template: 
    - bib
    - highlight
  style: ieee
  sort_by: year,month
  order: descending
  highlight: "Kraus, Oliver" 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
